### ISSUE TITLE
CssSyntaxError: Unknown word

### ISSUE THREAD

**Issue by jensenhertz** [gjbkz/rollup-plugin-embed-css#496]
I'm getting the following error when I try to build a project using embedCSS. As soon as I remove the plugin, everything compiles correctly, so it looks like this is something in embedCSS. I don't have any other plugins installed.

Any ideas?

```bash
CssSyntaxError: /backbone/backbone-swap-demo/src/ui/index.css:3:9: Unknown word
    at Input.error (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/input.js:148:16)
    at Parser.unknownWord (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/parser.js:540:22)
    at Parser.other (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/parser.js:164:12)
    at Parser.parse (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/parser.js:72:16)
    at parse (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/backbone/backbone-swap-demo/node_modules/.pnpm/postcss@8.4.16/node_modules/postcss/lib/processor.js:28:14)
    at compileCSS (file:///backbone/backbone-swap-demo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:42354:10)
    at async Object.transform (file:///backbone/backbone-swap-demo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:41869:55)
    at async transform (file:///backbone/backbone-swap-demo/node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:21911:16)
```

**index.css**
```css
html,body {
    margin:0;
    padding:0;
}

body {
    background-color: #F3F5FF;
    overflow: hidden;
}
```

**Comment by gjbkz** [comment]
There is no **rollup-plugin-embed-css** in the stack trace you provided: [rollup](https://www.npmjs.com/package/rollup) → [vite](https://www.npmjs.com/package/vite) → [postcss](https://www.npmjs.com/package/postcss). The CSS you provided looks fine so I don't know what is causing the problem. If everything compiles correctly without this plugin, then this plugin would be unnecessary.

**Comment by jensenhertz** [comment]
But isn't the point of this plugin to embed CSS into the bundle? Vite/rollup doesn't seem to do that out-of-the-box.

**Comment by gjbkz** [comment]
Do you need this plugin? Even without this plugin, Vite itself provides CSS import functionality: https://vitejs.dev/guide/features.html#css.

Vite doesn't depend on this plugin. If it did depend, [the download count for this plugin (~230/w)](https://www.npmjs.com/package/rollup-plugin-embed-css) would be as large as [Vite's (1,600,000/w)](https://www.npmjs.com/package/vite).

Run `npm ls rollup-plugin-embed-css` to see if your project depends on this plugin.

**Comment by jensenhertz** [comment]
Oh, perfect, thank you for pointing that out! I just started playing today with vite, so I missed the part where it inlines css automatically.
